import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { ArrowRight, Plus } from "lucide-react";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { EmptyState, ErrorState, Field, LoadingState, PageHeader } from "@/components/page-ui"; import { useSimbiData } from "@/lib/simbi-data";
export const Route = createFileRoute("/_authenticated/classes")({ head: () => ({ meta: [{ title: "Turmas — Simbi" }, { name: "description", content: "Organize suas turmas e acesse suas memórias pedagógicas." }, { property: "og:title", content: "Turmas — Simbi" }, { property: "og:description", content: "Suas turmas e registros de aula." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: ClassesPage });
function ClassesPage() { const { classes, students, records, loading, error, refresh, saveClass } = useSimbiData(); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [form,setForm]=useState({name:"",subject:"",grade:"",notes:""}); if(loading)return <LoadingState/>; if(error)return <ErrorState message={error} retry={()=>void refresh()}/>;
async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await saveClass(form);setOpen(false);setForm({name:"",subject:"",grade:"",notes:""});}finally{setBusy(false)}}
return <><PageHeader eyebrow="Organização" title="Turmas" description="Cada turma guarda seu histórico, pendências e observações." action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus/>Nova turma</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Criar turma</DialogTitle><DialogDescription>Somente as informações essenciais para começar.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Nome da turma"><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: 8º B"/></Field><Field label="Disciplina"><Input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Ex.: Matemática"/></Field><Field label="Série / ano"><Input required value={form.grade} onChange={e=>setForm({...form,grade:e.target.value})} placeholder="Ex.: 8º ano"/></Field><Field label="Observação (opcional)"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><Button size="lg" disabled={busy}>{busy?"Salvando...":"Criar turma"}</Button></form></DialogContent></Dialog>} />
{classes.length?<div className="divide-y divide-border border-y border-border">{classes.map(item=>{const latest=records.find(r=>r.class_id===item.id);return <Link key={item.id} to="/classes/$classId" params={{classId:item.id}} className="group grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 py-5"><div className="min-w-0"><h2 className="font-display text-2xl font-bold">{item.name}</h2><p className="mt-1 text-sm text-muted-foreground">{item.subject} · {item.grade}</p><p className="mt-4 truncate text-sm"><span className="text-muted-foreground">Último conteúdo: </span>{latest?.content??"Nenhum registro"}</p><p className="mt-1 text-xs text-muted-foreground">{students.filter(s=>s.class_id===item.id).length} alunos · {records.filter(r=>r.class_id===item.id&&r.pending).length} pendências</p></div><ArrowRight className="text-muted-foreground transition-transform group-hover:translate-x-1"/></Link>})}</div>:<EmptyState title="Nenhuma turma por aqui" text="Crie sua primeira turma para começar a registrar sua rotina docente." action={<Button onClick={()=>setOpen(true)}><Plus/>Criar turma</Button>}/>}</>;}
