import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, CheckCircle2, Clock3, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EmptyState, ErrorState, LoadingState, PageHeader, SectionTitle } from "@/components/page-ui";
import { formatDate, statusLabel, useSimbiData } from "@/lib/simbi-data";
export const Route = createFileRoute("/_authenticated/today")({ head: () => ({ meta: [{ title: "Hoje — Simbi" }, { name: "description", content: "Veja suas turmas recentes, aulas e pendências." }, { property: "og:title", content: "Hoje — Simbi" }, { property: "og:description", content: "Sua rotina docente em um só lugar." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: TodayPage });
function TodayPage() { const { profile, classes, students, records, loading, error, refresh } = useSimbiData(); if (loading) return <LoadingState />; if (error) return <ErrorState message={error} retry={() => void refresh()} />; const first = profile?.display_name.split(" ")[0] ?? "Professor"; const pending = records.filter((r) => r.pending).slice(0, 4); const recent = records.slice(0, 4); const registerTo = classes[0] ? `/classes/${classes[0].id}/record` : "/classes";
return <><PageHeader eyebrow="Hoje" title={`Olá, ${first}.`} description="O essencial para retomar sua rotina sem perder o fio da aula." action={<Button asChild size="icon" className="sm:hidden"><Link to={registerTo}><Plus /></Link></Button>} />
<Button asChild size="lg" className="mb-10 hidden sm:inline-flex"><Link to={registerTo}><Plus />Registrar aula</Link></Button>
<section className="mb-10"><SectionTitle aside={<Link to="/classes" className="text-sm font-semibold text-primary">Ver todas</Link>}>Turmas recentes</SectionTitle>{classes.length ? <div className="grid gap-px overflow-hidden border-y border-border bg-border sm:grid-cols-2">{classes.slice(0,4).map((item) => { const latest = records.find((r) => r.class_id === item.id); return <Link key={item.id} to="/classes/$classId" params={{ classId: item.id }} className="group bg-background p-5 transition-colors hover:bg-muted"><div className="flex items-start justify-between gap-3"><div><h3 className="font-display text-2xl font-bold">{item.name}</h3><p className="mt-1 text-sm text-muted-foreground">{item.subject} · {item.grade}</p></div><ArrowRight className="text-muted-foreground transition-transform group-hover:translate-x-1" size={19} /></div><p className="mt-5 text-xs font-bold uppercase text-muted-foreground">Último conteúdo</p><p className="mt-1 truncate text-sm font-medium">{latest?.content ?? "Nenhum registro ainda"}</p><p className="mt-3 text-xs text-muted-foreground">{students.filter((s) => s.class_id === item.id).length} alunos</p></Link>; })}</div> : <EmptyState title="Comece pela sua primeira turma" text="Crie uma turma para adicionar alunos e registrar aulas." action={<Button asChild><Link to="/classes"><Plus />Criar turma</Link></Button>} />}</section>
<div className="grid gap-10 md:grid-cols-2"><section><SectionTitle>Últimas aulas</SectionTitle><div className="divide-y divide-border border-y border-border">{recent.map((record) => { const room = classes.find((c) => c.id === record.class_id); return <Link key={record.id} to="/classes/$classId" params={{ classId: record.class_id }} className="flex gap-4 py-4"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-secondary text-primary"><BookOpen size={18} /></span><div className="min-w-0"><p className="truncate font-semibold">{record.content}</p><p className="mt-1 text-xs text-muted-foreground">{room?.name} · {formatDate(record.lesson_date)} · {statusLabel[record.status]}</p></div></Link>; })}{!recent.length && <p className="py-8 text-sm text-muted-foreground">Nenhuma aula registrada.</p>}</div></section>
<section><SectionTitle>Pendências</SectionTitle><div className="divide-y divide-border border-y border-border">{pending.map((record) => <div key={record.id} className="flex gap-4 py-4"><Clock3 className="mt-0.5 shrink-0 text-accent-foreground" size={19} /><div><p className="text-sm font-medium leading-6">{record.pending}</p><p className="mt-1 text-xs text-muted-foreground">{classes.find((c) => c.id === record.class_id)?.name}</p></div></div>)}{!pending.length && <div className="flex gap-3 py-8 text-sm text-muted-foreground"><CheckCircle2 size={19} />Nenhuma pendência registrada.</div>}</div></section></div></>; }
